epochs: 1
batch_size: 1024
input_sequence_length: 96
output_sequence_length: 24
dropout: 0.1
layers: [256, 128, 128]
l2_reg: 0.001
learning_rate: 0.001
preprocessing: True
exogenous: False
dataset: 'uci'
ffnn_type: 'simple'
train: False
detrend: True
recursive_forecast: True